### ISSUE TITLE
No moment 2 map

### ISSUE THREAD

**Issue by panstarrs** [kmhess/SoFiA-image-pipeline#83]
Hi, I notice that the moment 2 map is not produced by the current sip. I guess it won't be a problem for sip to add a make_mom2 function ? thanks.

**Comment by kmhess** [comment]
Yes, this should be an easy functionality to add, and I propose that we do it as an optional output rather than a default output since mom 2 maps are not useful in many cases (they may say more about bandwidth smearing than about the dispersion in the galaxy).  That said, if you have an example of a mom 2 map you like, or suggestions for color maps that are intuitive, etc, please share them.

**Comment by panstarrs** [comment]
Yeah, I agree that mom2 is not as useful as others for individual galaxies. How about something like Fig. 2(c) in https://arxiv.org/pdf/2303.17638.pdf ? To me, it looks intuitive when the dispersion gets increased, thanks.

**Comment by kmhess** [comment]
Hi @panstarrs, sorry for the very long delay in addressing this issue.  I've staged some changes in the mom2 branch, if you have the opportunity to test them and give feedback.
